# Generated by Django 6.0.5 on 2026-05-14 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyReconstructionSnapshot',
            fields=[
                ('snapshot_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='拓扑快照ID')),
                ('constellation_id', models.CharField(db_index=True, max_length=64, verbose_name='星座ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='重构发生时间')),
                ('is_updated', models.BooleanField(default=False, verbose_name='拓扑是否真的发生了更新')),
                ('network_link_switch_rate', models.FloatField(blank=True, null=True, verbose_name='全网链路切换率')),
                ('orbit_layer_switch_std_dev', models.FloatField(blank=True, null=True, verbose_name='轨道层间切换标准差')),
                ('avg_hops_before', models.FloatField(blank=True, null=True, verbose_name='重构前平均跳数')),
                ('avg_hops_after', models.FloatField(blank=True, null=True, verbose_name='重构后平均跳数')),
                ('avg_hop_reduction', models.FloatField(blank=True, null=True, verbose_name='平均跳数减少量')),
                ('avg_hop_reduction_rate', models.FloatField(blank=True, null=True, verbose_name='平均跳数减少率')),
                ('avg_delay_before_ms', models.FloatField(blank=True, null=True, verbose_name='重构前平均总时延(ms)')),
                ('avg_delay_after_ms', models.FloatField(blank=True, null=True, verbose_name='重构后平均总时延(ms)')),
                ('avg_delay_reduction_rate', models.FloatField(blank=True, null=True, verbose_name='平均总时延减少率')),
                ('pair_count', models.IntegerField(blank=True, null=True, verbose_name='业务需求对数量')),
                ('protected_link_count', models.FloatField(blank=True, null=True, verbose_name='受保护链路数量')),
                ('decision_time_ms', models.FloatField(blank=True, null=True, verbose_name='重构算法决策时间(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanningTaskDemand',
            fields=[
                ('constellation_id', models.CharField(db_index=True, max_length=64, verbose_name='星座ID')),
                ('task_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='规划任务ID')),
                ('task_type', models.CharField(default='Communication', max_length=50, verbose_name='任务类型')),
                ('src_gs_id', models.IntegerField(db_index=True, verbose_name='源地面站ID')),
                ('dst_gs_id', models.IntegerField(db_index=True, verbose_name='目的地面站ID')),
                ('demand_gbps', models.FloatField(verbose_name='带宽需求(Gbps)')),
                ('duration', models.FloatField(verbose_name='持续占用时长(s)')),
                ('task_priority', models.IntegerField(default=5, verbose_name='任务优先级')),
                ('arrival_sim_time', models.DateTimeField(db_index=True, verbose_name='仿真到达时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['constellation_id', 'arrival_sim_time'], name='simulation__constel_128268_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoutingDemand',
            fields=[
                ('constellation_id', models.CharField(db_index=True, max_length=64, verbose_name='星座ID')),
                ('generation_timestamp', models.DateTimeField(db_index=True, verbose_name='仿真生成批次时刻')),
                ('task_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='路由任务ID')),
                ('src_sat', models.IntegerField(db_index=True, verbose_name='源卫星ID')),
                ('dst_sat', models.IntegerField(db_index=True, verbose_name='目的卫星ID')),
                ('packet_size', models.FloatField(verbose_name='业务包大小(PacketSize)')),
                ('task_priority', models.IntegerField(default=5, verbose_name='业务优先级(TaskPriority)')),
                ('duration', models.FloatField(verbose_name='持续占用时长(Duration)')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='任务开始执行时间(StartTime)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['constellation_id', 'generation_timestamp'], name='simulation__constel_6daa37_idx')],
            },
        ),
        migrations.CreateModel(
            name='SimRealtimeLinkState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constellation_id', models.CharField(db_index=True, max_length=64, verbose_name='星座ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='仿真更新时刻')),
                ('src_sat', models.IntegerField(db_index=True, verbose_name='源卫星ID')),
                ('dst_sat', models.IntegerField(db_index=True, verbose_name='目的卫星ID')),
                ('link_distance', models.FloatField(verbose_name='链路距离(km)')),
                ('current_flow', models.FloatField(verbose_name='当前流量(Gbps)')),
                ('left_capacity', models.FloatField(verbose_name='剩余容量')),
                ('queue_delay', models.FloatField(verbose_name='排队时延(ms)')),
                ('heat_value', models.FloatField(verbose_name='链路热力值')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['constellation_id', 'timestamp'], name='simulation__constel_7be7f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SimRealtimeNodeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constellation_id', models.CharField(db_index=True, max_length=64, verbose_name='星座ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='仿真更新时刻')),
                ('sat_id', models.IntegerField(db_index=True, verbose_name='卫星ID')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('flow', models.FloatField(verbose_name='当前总流量(Gbps)')),
                ('energy_ratio', models.FloatField(verbose_name='电池电量(%)')),
                ('congestion', models.FloatField(verbose_name='节点拥塞程度')),
                ('heat_flow', models.FloatField(verbose_name='节点热力值')),
                ('ground_station_number', models.IntegerField(blank=True, null=True, verbose_name='直连地面站数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['constellation_id', 'timestamp'], name='simulation__constel_67e7e3_idx'), models.Index(fields=['sat_id', 'timestamp'], name='simulation__sat_id_886c54_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopologyLinkPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constellation_id', models.CharField(db_index=True, max_length=64, verbose_name='星座ID')),
                ('src_sat', models.IntegerField(verbose_name='源卫星 ID')),
                ('dst_sat', models.IntegerField(verbose_name='目的卫星 ID')),
                ('predict_invoke_time', models.DateTimeField(db_index=True, verbose_name='发起预测的时间')),
                ('predict_target_time', models.DateTimeField(verbose_name='预测发生的目标长时刻')),
                ('capacity', models.FloatField(verbose_name='预测剩余容量(Capacity)')),
                ('survival', models.FloatField(verbose_name='预测链路存活度(Survival)')),
                ('heat_value', models.FloatField(verbose_name='预测热力值(HeatValue)')),
                ('link_availability', models.FloatField(verbose_name='可用性评分(LinkAvailability)')),
                ('inference_time', models.FloatField(blank=True, null=True, verbose_name='算法批量推理耗时(s)')),
            ],
            options={
                'indexes': [models.Index(fields=['constellation_id', 'src_sat', 'dst_sat', 'predict_target_time'], name='simulation__constel_bf2110_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopologyLinkState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_sat', models.IntegerField(db_index=True, verbose_name='源卫星')),
                ('dst_sat', models.IntegerField(db_index=True, verbose_name='目标卫星')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='距离')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='总容量')),
                ('left_capacity', models.FloatField(blank=True, null=True, verbose_name='剩余容量')),
                ('current_flow', models.FloatField(blank=True, null=True, verbose_name='当前流量')),
                ('propagation_delay', models.FloatField(blank=True, null=True, verbose_name='传播时延')),
                ('queue_delay', models.FloatField(blank=True, null=True, verbose_name='排队时延')),
                ('transmission_delay', models.FloatField(blank=True, null=True, verbose_name='传输时延')),
                ('packet_loss_rate', models.FloatField(blank=True, null=True, verbose_name='丢包率')),
                ('heat_value', models.FloatField(blank=True, null=True, verbose_name='热力值')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='simulation_api.topologyreconstructionsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='RoutingResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('route_path', models.JSONField(verbose_name='规划的路径节点数组')),
                ('queue_delay_arr', models.JSONField(verbose_name='每一跳的排队时延(数组)')),
                ('transmission_delay_arr', models.JSONField(verbose_name='每一跳的传输时延(数组)')),
                ('packet_loss_rate_arr', models.JSONField(verbose_name='每一跳的丢包率(数组)')),
                ('total_hop_count', models.IntegerField(verbose_name='总跳数')),
                ('path_total_cost', models.FloatField(verbose_name='路径总代价')),
                ('end_to_end_delay', models.FloatField(verbose_name='端到端总时延')),
                ('isl_valid_rate', models.FloatField(verbose_name='星间链路有效率')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='路由起算/生效时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='路由结束/失效时间')),
                ('inference_time_seconds', models.FloatField(blank=True, null=True, verbose_name='算法推理耗时(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='routing_results', to='simulation_api.routingdemand', verbose_name='关联的路由任务ID')),
            ],
            options={
                'indexes': [models.Index(fields=['task'], name='simulation__task_id_df5002_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskPlanningResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('constellation_id', models.CharField(db_index=True, max_length=64, verbose_name='星座ID')),
                ('src', models.CharField(max_length=64, verbose_name='源端点ID')),
                ('dst', models.CharField(max_length=64, verbose_name='目标端点ID')),
                ('demand_gbps', models.FloatField(verbose_name='分配的带宽(Gbps)')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='失败或降级等原因')),
                ('avg_delay_ms', models.FloatField(verbose_name='加权平均时延(ms)')),
                ('capacity_status', models.CharField(max_length=20, verbose_name='容量分配状态(OK/FAILED)')),
                ('capacity_max_util_after', models.FloatField(verbose_name='分配后最大容量占用率')),
                ('capacity_total_overflow', models.FloatField(verbose_name='总超载量')),
                ('overflow_amount', models.FloatField(verbose_name='网络溢出量')),
                ('jitter_ms', models.FloatField(verbose_name='抖动时延估计(ms)')),
                ('max_link_utilization_after', models.FloatField(verbose_name='链路最大占用率')),
                ('decision_total_ms', models.FloatField(verbose_name='推理决策总耗时(ms)')),
                ('allocations', models.JSONField(verbose_name='具体路径和分流方案数组')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='planning_results', to='simulation_api.planningtaskdemand', verbose_name='关联的规划需求ID')),
            ],
            options={
                'indexes': [models.Index(fields=['task'], name='simulation__task_id_e12e41_idx'), models.Index(fields=['constellation_id'], name='simulation__constel_423ac3_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopologyDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_sat', models.IntegerField(db_index=True, verbose_name='源卫星')),
                ('dst_sat', models.IntegerField(db_index=True, verbose_name='目标卫星')),
                ('change_type', models.CharField(choices=[('ADD', 'Added'), ('DEL', 'Deleted')], max_length=10, verbose_name='变化类型')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='differences', to='simulation_api.topologyreconstructionsnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'change_type'], name='simulation__snapsho_e5fa5d_idx')],
            },
        ),
    ]
