# Generated by Django 6.0.5 on 2026-05-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyPredictionAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constellation_id', models.CharField(db_index=True, max_length=64, verbose_name='星座ID')),
                ('window_start_time', models.DateTimeField(db_index=True, verbose_name='评估窗口起始时间')),
                ('window_end_time', models.DateTimeField(verbose_name='评估窗口结束时间')),
                ('accuracy', models.FloatField(verbose_name='总体预测准确率')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='精确率')),
                ('recall', models.FloatField(blank=True, null=True, verbose_name='召回率')),
                ('total_evaluated_links', models.IntegerField(verbose_name='参与评估的总链路数')),
            ],
            options={
                'db_table': 'sim_prediction_accuracy',
            },
        ),
    ]
